### PR TITLE
DSGj example

### PR DESCRIPTION
**Pull request by ritikarawlani**
Closes # 

## 📑 Description
Adding DSGj example for detached. Readme gives step by step instructions and files for each step are included.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] All the tests have passed
- [ ] I have selected a committee co-chair to review the PR

### CODE REVIEW

**Review by JohnMoehrke — APPROVED** [review]
looks good to me. The readme might be better as a README.MD. I think @lukeaduncan was going to convert it.

**Comment by lukeaduncan** [comment]
> looks good to me. The readme might be better as a README.MD. I think @lukeaduncan was going to convert it.

README has been converted and I added links to the "see file" text.

**Comment by JohnMoehrke** [comment]
@litlfred we leave it to you for final approval.

**Comment by ritikarawlani** [comment]
Reviewed with Carl, needs some revisions, will modify on Monday

**Comment by ritikarawlani** [comment]
I've made updates - @litlfred  can you approve

**Review by litlfred — APPROVED** [review]

**Pull request merged**
